version: '3.8'

services:
  cub3d:
    container_name: cub3d
    build:
      context: .
    volumes:
      - ./program:/home/program
    working_dir: /home/program
    environment:
      - DISPLAY=host.docker.internal:0
    command: /bin/bash
    tty: true